workflows:
  default-workflow:
    name: Workflow AWS S3
    environment:
      vars:
        AWS_ACCESS_KEY_ID: Encrypted(Z0FBQUFBQmdrRGc5Vi00MG9rOE5kVEM3aEtxb3E2OFNydy1feUxKYTJjdUxCbC15MzI5X0szMzh0MXFNbGozcmhLbnUxYmtfYmIxOW9yU2pRZndNRnk5aHZQaGFlanhqaFVka2szTmRIVFhDM0dlTmo5SVBURUU9)
        AWS_SECRET_ACCESS_KEY: Encrypted(Z0FBQUFBQmdrRGh1b1AtWkVPS1NrUDZSS05vRmJuNFg1WVF0YkRxWWpvQmlwRG9iUmpBemlvcjRzeGg0dWNtcElibVRrUmtRYW40Yi1WSmZYX1dqN2VyZGJSVmR2TlJBRGN2Wnl5dGx2QllnNTJGMHNQTDBadWY1MFdkd0xLcXlZX2x3NTBSR2V4bFc=)
      flutter: dev
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - flutter config --enable-web
      - flutter test
      - |
        # build web
        flutter build web --release
        cd build/web
        7z a -r ../web.zip ./*
        cd $FCI_BUILD_DIR/build/
        sudo pip3 install awscli --upgrade
        aws s3 sync web/ s3://bucket-rogerio/
    artifacts:
      - build/**/outputs/**/mapping.txt
      - build/web.zip
      - flutter_drive.log